[package]
org = "thenusan"
name = "patient_matching_usecase"
version = "0.1.0"
distribution = "2201.5.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"

[persist]
datastore = "mysql"
module = "patient_matching_usecase"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist-native"
version = "0.3.1"

# [[dependency]]
# org = "ballerinax"
# name = "health.fhir.r4utils.fhirpath"
# version = "1.0.2"
# repository = "local"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4utils.patientmatching"
version = "0.1.0"
repository = "local"
